# Generated by Django 5.2.1 on 2025-05-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('roll_no', models.CharField(max_length=50)),
                ('certificate', models.URLField()),
                ('certificate_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
