# Generated by Django 5.2.1 on 2025-05-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0002_certificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
