# Generated by Django 5.2.1 on 2025-05-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0004_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(editable=False, max_length=9, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
