# Generated by Django 5.2.1 on 2025-05-30 15:37

import authority.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0005_mymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='unique_id',
            field=models.CharField(default=authority.models.generate_unique_id, editable=False, max_length=6, unique=True),
        ),
    ]
