# Generated by Django 5.2.1 on 2025-06-04 10:48

import authority.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
       ('authority', '0006_remove_mymodel_created_at_alter_mymodel_name_and_more'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='MyModel',
        # ),
        migrations.AlterField(
            model_name='Certificate',
            name='certificate_id',
            field=models.CharField(default=authority.models.generate_unique_id, editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
