# Generated by Django 5.2.1 on 2025-05-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0006_remove_mymodel_created_at_alter_mymodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Certificate',
            name='certificate',
            field=models.URLField(blank=True, null=True),
        ),
    ]
