# Generated by Django 5.2.1 on 2025-06-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0007_alter_certificate_certificate'),
        ('authority', '0007_delete_mymodel_alter_certificate_certificate_id'),
    ]

    operations = [
    ]