# Generated by Django 5.2.1 on 2025-06-03 18:20

import authority.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0007_alter_certificate_certificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.CharField(default=authority.models.generate_unique_id, editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
