# Generated by Django 5.2.1 on 2025-06-05 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('authority', '0008_delete_mymodel_alter_certificate_certificate_id'),
        ('authority', '0008_merge_20250605_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='status',
        ),
    ]