# Generated by Django 5.2.1 on 2025-06-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0008_merge_20250605_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
