# Generated by Django 5.2.1 on 2025-06-06 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0009_alter_certificate_certificate_id'),
        ('authority', '0009_remove_certificate_status'),
    ]

    operations = [
    ]