# Generated by Django 5.2.1 on 2025-06-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0009_alter_certificate_certificate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('superadmin', 'Super Admin'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
