# Generated by Django 5.2.1 on 2025-06-06 16:44

import authority.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0010_merge_20250606_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.CharField(default=authority.models.generate_unique_id, editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
