# Generated by Django 5.2.1 on 2025-06-07 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0010_merge_20250606'),
        ('authority', '0012_merge_conflicts'),
    ]

    operations = [
    ]
