# Generated by Django 5.2.1 on 2025-06-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0013_merge_0010_merge_20250606_0012_merge_conflicts'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='MyModel',
        # ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_users',
            field=models.BooleanField(default=False),
        ),
    ]
