# Generated by Django 5.2.1 on 2025-06-13 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0014_delete_mymodel_customuser_can_manage_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
