# Generated by Django 5.2.1 on 2025-06-18 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0015_add_role_field'),
        ('authority', '0015_remove_customuser_can_manage_users'),
    ]

    operations = [
    ]
