# Generated by Django 5.2.1 on 2025-06-18 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        #('authority', '0015_delete_mymodel'),
        ('authority', '0015_remove_customuser_can_manage_users'),
    ]

    operations = [
    ]
