# Generated by Django 5.2.1 on 2025-06-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
       # ('authority', '0016_delete_mymodel'),
        ('authority', '0016_merge_20250618_1400'),
    ]

    operations = [
    ]
