# Generated by Django 5.2.1 on 2025-06-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0017_merge_0016_delete_mymodel_0016_merge_20250618_1400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
