# Generated by Django 5.2.1 on 2025-07-07 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0018_club_event'),
        ('authority', '0018_merge_20250623_1326'),
    ]

    operations = [
    ]
