# Generated by Django 5.2.1 on 2025-07-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0019_merge_0018_club_event_0018_merge_20250623_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_pdf',
            field=models.URLField(blank=True, null=True),
        ),
    ]
