# Generated by Django 5.2.1 on 2025-07-09 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0018_delete_mymodel'),
        ('authority', '0019_merge_0018_club_event_0018_merge_20250623_1326'),
    ]

    operations = [
    ]
