# Generated by Django 5.2.1 on 2025-07-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0020_merge_20250709_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
