# Generated by Django 5.2.1 on 2025-07-10 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0020_event_event_image_event_event_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='head',
            new_name='club_head',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='name',
            new_name='club_name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='club',
            new_name='club_id',
        ),
        migrations.AddField(
            model_name='event',
            name='coordinator_name1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='coordinator_name2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.URLField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
