# Generated by Django 5.2.1 on 2025-07-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0021_certificate_certificate_url'),
        ('authority', '0021_rename_head_club_club_head_and_more'),
    ]

    operations = [
    ]
