# Generated by Django 5.2.1 on 2025-07-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0022_merge_20250725_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='coordinator_name',
            new_name='coordinator1',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='coordinator_name1',
            new_name='coordinator2',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='coordinator_name2',
            new_name='coordinator3',
        ),
        migrations.AddField(
            model_name='event',
            name='coordinator4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='participantList',
            field=models.URLField(blank=True, null=True),
        ),
    ]
